# Use docker-compose for local debugging/testing.
version: "3.3"
services: 
  backend:
    build: backend
    restart: always
    expose:
      - 8080
  frontend:
    build: frontend
    restart: always
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
    ports:
      - "8080:8080/tcp"
    links:
      - backend
