# Do not deploy these resources on the same cluster where the frontend is running.
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
      - name: backend1
        image: alexandreroman/k8s-session-affinity-backend
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "9000"
        ports:
        - containerPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
    spec:
      containers:
      - name: backend2
        image: alexandreroman/k8s-session-affinity-backend
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "9000"
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: backend1-lb
  namespace: backend
  labels:
    app: backend1
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: backend1
---
apiVersion: v1
kind: Service
metadata:
  name: backend2-lb
  namespace: backend
  labels:
    app: backend2
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: backend2
